# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            iamdionysus blog
tagline:          'to study'
description:      'organize based on Jekyll and Hyde'
url:              http://iamdionysus.github.io

author:
  name:           'iamdionysus'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde