# Dependencies
markdown:         redcarpet
highlighter: 	  pygments

# Permalinks
permalink:        pretty

# Setup
title:            'dionysus'
tagline:          'to study'
description:      'organize everything with Jekyll and Hyde'
url:              http://iamdionysus.github.io

author:
  name:           'iamdionysus'
  url:            

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde